# Generated by Django 6.0.3 on 2026-04-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('days', models.IntegerField()),
                ('price_rub', models.IntegerField()),
                ('price_stars', models.IntegerField()),
                ('price_usdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает активации'), ('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='pending', max_length=16)),
                ('panel_uuid', models.CharField(blank=True, max_length=36)),
                ('sub_id', models.CharField(blank=True, max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.telegramuser')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
