# Generated by Django 6.0.3 on 2026-04-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price_stars',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_usdt',
        ),
    ]
