# Generated by Django 6.0.3 on 2026-04-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='yookassa', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_charge_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
