# Generated by Django 4.2.30 on 2026-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
